SET(QWT_INCLUDE_DIR NOTFOUND)
SET(QWT_LIBRARY NOTFOUND)
MARK_AS_ADVANCED(QWT_INCLUDE_DIR QWT_LIBRARY)

FIND_PATH(QWT_INCLUDE_DIR qwt.h)
FIND_LIBRARY(QWT_LIBRARY qwt)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Qwt DEFAULT_MSG QWT_LIBRARY QWT_INCLUDE_DIR)

IF(QWT_INCLUDE_DIR AND QWT_LIBRARY)
    ADD_LIBRARY(Qwt SHARED IMPORTED)
    SET_TARGET_PROPERTIES(Qwt PROPERTIES
        IMPORTED_LOCATION ${QWT_LIBRARY}
        INTERFACE_INCLUDE_DIRECTORIES ${QWT_INCLUDE_DIR}
    )
ENDIF()
